app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: ${APP_CONFIG_app_baseUrl}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: ${APP_CONFIG_backend_baseUrl}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    pluginDivisionMode: schema

integrations:
  github:
    - host: github.com
      # In production we use an app for secure auth
      apps:
        - $include: github-secrets/github-app-backstage-skip-credentials.yaml

proxy:
  '/xkcd-proxy':
    target: https://xkcd.com/
  '/opencost':
    target: "http://opencost.opencost.svc.cluster.local:9090"
  '/lighthouse':
    target: http://lighthouse-audit-service.lighthouse-audit-service.svc.cluster.local:3003

lighthouse:
  baseUrl: /api/proxy/lighthouse

opencost:
  baseUrl: /api/proxy/opencost/model

catalog:
  providers:
    microsoftGraphOrg:
      default:
        tenantId: 7f74c8a2-43ce-46b2-b0e8-b6306cba73a3
        queryMode: 'advanced'
        user:
          filter: accountEnabled eq true and userType eq 'member'
        group:
          filter: >
            startswith(displayName, 'AAD - TF')
        schedule:
          frequency: PT1H
          timeout: PT50M
        clientId: ${ENTRA_ID_SP_APP_ID}
        clientSecret: ${ENTRA_ID_SP_CLIENT_SECRET}

auth:
  environment: production
  providers:
    oauth2Proxy:
      production: {}
    google:
      production:
        clientId: ${GOOGLE_OAUTH_CLIENT_ID}
        clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}

cors:
  origin: ${APP_CONFIG_app_baseUrl}
