site_name: Backstage
site_description: 'Documentation for SKIPs Backstage'
repo_url: https://github.com/kartverket/kartverket.dev
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Identity: 'overview/identity.md'
  - Getting Started:
      - Using the catalog: 'getting-started/using-the-catalog.md'
      - Adding your documentation: 'getting-started/techdocs.md'
