
version: '3'
services:
  proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    network_mode: host
    #env_file:
    #  - .env
    command: >-
      --reverse-proxy=true
      --config /oauth2-proxy.cfg
      --alpha-config /oauth2-proxy-alpha-config.yaml
    ports:
      - 4180:4180
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
      - "./oauth2-proxy-alpha-config.yaml:/oauth2-proxy-alpha-config.yaml"
