server:
  BindAddress: '0.0.0.0:4180'
metricsServer:
  BindAddress: '0.0.0.0:44180'

upstreamConfig:
  upstreams:
    - id: backstage-api
      path: /api/
      uri: http://localhost:7007
    - id: backstage-frontend
      path: /
      uri: http://localhost:3000
injectRequestHeaders:
  - name: x-auth-request-email
    values:
      - claim: email

injectResponseHeaders:
  - name: x-auth-request-email
    values:
      - claim: email

providers:
  - id: github
    name: github
    clientID:
    clientSecret:
    oidcConfig:
      issuerURL: https://token.actions.githubusercontent.com
      emailClaim: email
    provider: github
