server:
  BindAddress: '0.0.0.0:4180'
metricsServer:
  BindAddress: '0.0.0.0:44180'

upstreamConfig:
  upstreams:
    - id: backstage-api
      path: /api/
      uri: http://localhost:7007
    - id: backstage-frontend
      path: /
      uri: http://localhost:3000
injectRequestHeaders:
  - name: x-auth-request-email
    values:
      - claim: email

injectResponseHeaders:
  - name: x-auth-request-email
    values:
      - claim: email

providers:
  - id: azure
    name: azure
    clientID:
    clientSecret:
    azureConfig:
      tenant: 7f74c8a2-43ce-46b2-b0e8-b6306cba73a3
    oidcConfig:
      issuerURL: https://login.microsoftonline.com/7f74c8a2-43ce-46b2-b0e8-b6306cba73a3/v2.0
      emailClaim: email
      groupsClaim: groups
      userIDClaim: email
      audienceClaims:
        - aud
    provider: azure
    scope: "openid email profile"
