site_name: Backstage
site_description: Documentation for ${{values.repoUrl | parseRepoUrl | pick('repo')}}
repo_url: https://github.com/kartverket/${{values.repoUrl | parseRepoUrl | pick('repo')}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Index:
    - 'index.md'