apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    backstage.io/linguist: ${{values.repoUrl}}
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}